config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope '(:locale)', locale: /en|ar|es/ do

    root to: 'pages#index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :pages, only: %i[index create destroy]

    resources :articles, only: %i[index show]

    resources :stories, only: %i[index show]

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  extend FriendlyId

  LANGUAGES = %w[ea en].freeze

  validates :title, :description, presence: true, length: { minimum: 10 }
  validates :locale,  inclusion: { in: LANGUAGES, allow_nil: false }

  friendly_id :title, use: :slugged

  mount_uploader :photo, PhotoUploader

  private

  def locale_enum
     %w[ea en]
  end

end

app/models/story.rb
class Story < ApplicationRecord

  extend FriendlyId

  LANGUAGES = %w[ea en].freeze

  validates :title, :description, presence: true, length: { minimum: 10 }
  validates :locale,  inclusion: { in: LANGUAGES, allow_nil: false }

  friendly_id :title, use: :slugged

  mount_uploader :photo, PhotoUploader

  def locale_enum
     %w[ea en]
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  validates :email, email_format: { message: "doesn't look like an email address" }, presence: true
  validates :name, presence: true

  after_create :send_welcome_email
  after_create :subscribe_to_newsletter, if: :production?

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

  def subscribe_to_newsletter
    SubscribeToNewsletterService.new(self).call
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :set_locale

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end

  def destroy_user_if_current_user
    if current_user
      unless current_user.admin
        sign_out(current_user)
      end
    end
    @user = User.new
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :destroy_user_if_current_user, only: %i[index show]

  def index
    @articles = Article.all
    policy_scope(Article)
  end

  def show
    @article = Article.friendly.find(params[:id])
    authorize @article
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, :locale, :photo, :photo_cache)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index]
  before_action :destroy_user_if_current_user, only: [:index]

  def index
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :name)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :destroy_user_if_current_user, only: %i[index show]

  def index
    @story = Story.all
    policy_scope(Story)
  end

  def show
    @story = Story.friendly.find(params[:id])
    authorize @story
  end

  private

  def story_params
    params.require(:story).permit(:title, :description, :locale, :photo, :photo_cache)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="Undercut">
<meta name="application-name" content="Undercut">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/articles/index.html.erb
<% content_for :title, I18n.t('views.articles.index.articles') %>

  <div id='main' role='main'>

    <div class="banner-small" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.0) 0%, rgba(0,36,61,0.2) 50%), url('<%= cl_image_path("at/ship.jpg", :client_hints=>true, :transformation=>[{:width=>1700, :height=>850, :dpr=>"auto", :gravity=>"south", :crop=>"fill"}]) %>');">
      <div>
         <h1 class='big fadeInRightBig animated'>Blog</h1>
      </div>
    </div>

    <div id='main-content'>
      <div class='container'>
        <div class="description-center">
          <%#= link_to "Olivia, write something!", new_article_path, class: "btn btn-primary" %>
        </div>
        <div class='row'>
          <div class='col-sm-12 col-sm-12 col-md-12'>
            <div class='text-boxes'>

            <% @articles.each do |article| %>
              
              <div class='row text-box text-box-title-above'>
                <div class='col-sm-12'>
                  <h2>
                  <%= link_to article.title, article_path(article), class: '', style:'text-decoration: none' %>
                  </h2>
                  <div class='toolbar'>
                    <div class='btn btn-link' style:'text-decoration: none'>
                      
                    </div>
                  </div>
                  <div class='row'>
                    <div class='col-sm-3'>
                    <p class:'text-center'></p>
                      <%= cl_image_tag(article.photo.presence || "at/apple.jpg", 
                          :client_hints=>true, 
                          :transformation=>[{:height => 180, :width => 300, :dpr=>"auto", :gravity=>"", :crop=>"fill"}], 
                          :class => "img-responsive center-block img-rounded-half" ) %>
                    </div>
                    <div class='col-sm-9'>
                      <p> <%= article.description.first(500).html_safe %></p>
                      <i class='fa fa-calendar'></i>
                      <%= article.created_at.strftime("%B %d %Y") %> 
                      
                      <%= link_to "Mas informacion", article_path(article), class: "btn btn-contrast" %>
                      
                    </div>
                  </div>
                  <hr class='hr-half'>
                </div>
              </div>
              
              <% end %>

            </div>
          </div>
      </div>
    </div>
    <div class='fade' id='scroll-to-top'>
      <i class='fa fa-chevron-up'></i>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<% content_for :title, "#{@article.title}" %>

  <div id='main' role='main'>

    <div class="banner-small" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.0) 0%, rgba(0,36,61,0.2) 50%), url('<%= cl_image_path( @article.photo.presence || "at/apple.jpg", :client_hints=>true, :transformation=>[{:width=>1700, :height=>850, :dpr=>"auto", :gravity=>"south", :crop=>"fill"}]) %>');">
      <div>
         <h1 class='big fadeInRightBig animated'> <%=  @article.title %></h1>
      </div>
    </div>

        <div id='main-content'>
          <div class='container'>
            <div class='row'>
              <div class='col-sm-12'>
              <!-- <div class='col-md-pull-3 col-sm-pull-4 col-sm-8 col-md-9'> -->
                <div class='text-boxes'>
                  <div class='row text-box text-box-title-above text-box-big-image'>
                    <div class='col-sm-12'>
                      
                      <h2 class='title'>
                      </h2>
                      <div class='toolbar'>
                        <i class='fa fa-calendar'></i>
                        <%= @article.created_at.strftime("%B %d %Y") %> 
                        </a>
                      </div>
                      <div class='row'>
            
                  </div>
                  <div class='row padded'>
                    <div class='col-sm-12'>

                      <%= @article.description.html_safe %>

                    </div>
                  </div>
                  <div class='row'>
                    <div class='col-sm-12'>
                      <div class='author-box'>
                        <div class='row'>
                          <div class='col-sm-3 col-lg-2'>
                            <%= cl_image_tag 'veronica/cristina.jpg', width: 200, height: 200, crop: :thumb, gravity: :face , class: "responsive-avatar text-center-xs"  %>
                          </div>
                          <div class='col-sm-9 col-lg-10'>
                            <h3 class='title'>About the author</h3>
                            <p> I am a self-made woman entrepreneur and proficient linguist in English, Spanish, French, Italian, Catalan and Rumanian. I am a team worker, with high compromise, responsibility and positive attitude to achieve short and long-term objectives. I apply constant effort in the areas of productivity and quality of every performed work. I am also an entrepreneur, polifacetic and charismatic English teacher. I am willing to continue progressing in my teaching career and combine it with my other passion: entrepreneurship. Creative, ambitious and energetic, always ready to roll sleeves up and establish plans and solutions in order to achieve strategic business initiatives and deliver results. I have total availability at the moment and may be contacted in the referred email anytime.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class=''>
                  <%= link_to 'Back', articles_path, class: "btn btn-primary"  %>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
        <div class='fade' id='scroll-to-top'>
          <i class='fa fa-chevron-up'></i>
        </div>
      </div>

    </div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title><%= yield(:title) %></title>
    <%= render 'favicon' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="utf-8">


    <!-- Mobile Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">



    <!-- Web Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:700,400,300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Maven+Pro" rel="stylesheet">


    <%= stylesheet_link_tag    'application', media: 'all' %>
    
    <!-- Facebook Pixel Code -->
    <script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
    n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
    document,'script','https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '1323542817661636'); // Insert your pixel ID here.
    fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=1323542817661636&ev=PageView&noscript=1"
    /></noscript>
    <!-- DO NOT MODIFY -->
    <!-- End Facebook Pixel Code -->
    
  </head>

    <!-- body classes:  -->
  <!-- "boxed": boxed layout mode e.g. <body class="boxed"> -->
  <!-- "pattern-1 ... pattern-9": background patterns for boxed layout mode e.g. <body class="boxed pattern-1"> -->
  <!-- "transparent-header": makes the header transparent and pulls the banner to top -->
  <!-- "gradient-background-header": applies gradient background to header -->
  <!-- "page-loader-1 ... page-loader-6": add a page loader to the page (more info @components-page-loaders.html) -->

   <body class="no-trans front-page transparent-header">

    <!-- move this to the bottom once remove js home page -->
    <%= javascript_include_tag 'application' %>

    <%= render 'shared/navbar_selector' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    <script async src="//cdn.trackduck.com/toolbar/prod/td.js" data-trackduck-id="5878d3419257f0e95e9ba1de"></script>

    <!-- google analitics -->

    <script>

      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-89702518-2', 'auto');
      ga('send', 'pageview');

    </script>
    
  </body>
</html>

app/views/pages/_demo.html.haml
:scss

  .picture {
    margin-top:20px;
  }


#demo
/ section start
/ ================
%section.section.clearfix
  .container
    .separator-2
    .row
      .col-md-6
        / accordion start
        / ================
        #accordion.panel-group.collapse-style-1
          .panel.panel-default
            .panel-heading
              %h4.panel-title
                %a.collapsed{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseOne"}
                  %i.fa.fa-question-circle-o.pr-10
                  = t '.What_is_Respira?'
            #collapseOne.panel-collapse.collapse
              .panel-body
                = t '.info_00'
                %br/
                %br/
                = t '.info_01'
          .panel.panel-default
            .panel-heading
              %h4.panel-title
                %a.collapsed{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseTwo"}
                  %i.fa.fa-road.pr-10
                  = t '.background'
            #collapseTwo.panel-collapse.collapse
              .panel-body
                = t '.info_1'
          .panel.panel-default
            .panel-heading
              %h4.panel-title
                %a.collapsed{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseThree"}
                  %i.fa.fa-rocket.pr-10
                  = t '.innovation'
            #collapseThree.panel-collapse.collapse
              .panel-body
                = t '.info_2'
                %br/
                %br/
                = t '.info_3'
          .panel.panel-default
            .panel-heading
              %h4.panel-title
                %a.collapsed{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseFour"}
                  %i.fa.fa-area-chart.pr-10
                  = t '.real-time'
            #collapseFour.panel-collapse.collapse
              .panel-body
                = t '.info_4'
          .panel.panel-default
            .panel-heading
              %h4.panel-title
                %a.collapsed{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseFive"}
                  %i.fa.fa-child.pr-10
                  = t '.wearability'
            #collapseFive.panel-collapse.collapse
              .panel-body
                = t '.info_5'
          .panel.panel-default
            .panel-heading
              %h4.panel-title
                %a.collapsed{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseSix"}
                  %i.fa.fa-bullseye.pr-10
                  = t '.our_goal'
            #collapseSix.panel-collapse.collapse.in
              .panel-body
                = t '.info_6'
        / accordion end
      .col-md-6
        = cl_image_tag("respira/dashboard_mobile1.png", :class => "picture", :client_hints=>true, :transformation=>[{:dpr=>"auto"}])
  .row
    .col-xs-12.col-md-push-2.col-md-4
      .style-2.mb-20.shadow.bordered.light-gray-bg.text-center
        .overlay-container
      
    .col-xs-12.col-md-push-2.col-md-4
      .image-box.style-2.mb-20.shadow.bordered.light-gray-bg.text-center
        .overlay-container
          
  / section start
  / ================
  %section.section.dark-bg.clearfix
    .container
      .row
        .col-md-12
          .call-to-action.text-center
            .row
              .col-sm-12
                %h1.title
                  = t '.cta'
                %p{:style => "font-style: italic;"} Gary Player
                %p
  / section end

app/views/pages/_features.html.haml
#features
%section.pv-30.padding-bottom-clear.clearfix
  .container
    .row
      .col-md-8.col-md-offset-2
        %h2.text-center
          %strong
            = t '.features_moto'
        .separator
        %p.large.text-center
          = t '.features_subtitle'
  .container
    %section.pv-30.padding-bottom-clear.clearfix
      .container
        .row
          .col-sm-4
            .image-box.style-2.mb-20.shadow.bordered.light-gray-bg.text-center
              .overlay-container
                = cl_image_tag("respira/shirt.jpg", :client_hints=>true, :transformation=>[{:dpr=>"auto", :height=>1350, :width=>2000, :y=>0, :x=>400, :crop=>"crop"}])
                -# .overlay-to-top
                  %p.small.margin-clear
                    %em
                      = t '.feature_hidden_1'
              .body
                %h3
                  = t '.wearable'
                .separator
                %p
                  = t '.feature_1'
          .col-sm-4
            .image-box.style-2.mb-20.shadow.bordered.light-gray-bg.text-center
              .overlay-container
                = cl_image_tag("respira/Natural.jpg", :client_hints=>true, :transformation=>[{:dpr=>"auto", :height=>1400, :width=>2000, :y=>-50, :x=>500, :crop=>"crop"}])
                -# .overlay-to-top
                  %p.small.margin-clear
                    %em
                      = t '.feature_hidden_2'
              .body
                %h3
                  = t '.real-time_feedback'
                .separator
                %p
                  = t '.feature_2'
          .col-sm-4
            .image-box.style-2.mb-20.shadow.bordered.light-gray-bg.text-center
              .overlay-container
                = cl_image_tag("respira/mobile.jpg", :client_hints=>true, :transformation=>[{:dpr=>"auto", :height=>1350, :width=>2000, :y=>100, :x=>150, :crop=>"crop"}])
                -# .overlay-to-top
                  %p.small.margin-clear
                    %em
                      = t '.feature_hidden_3'
              .body
                %h3
                  = t '.build_habits'
                .separator
                %p
                  = t '.feature_3'
        %br/






app/views/pages/_home.html.haml
:sass
  .logo-font-respira
    font-family: 'Maven Pro', sans-serif
    color: white!important
    font-size: 60px !important
    text-transform: lowercase !important 


#banner
-# .banner{:style => "background-image: linear-gradient(210deg, rgba(0,101,168,0.1) 20%, rgba(0,36,61,0.5) 50%), url('#{cl_image_path("respira/banner.jpg", :client_hints=>true, :transformation=>[{:x=>1500, :y=>100, :width=>2000, :height=>1000, :dpr=>"auto", :crop=>"crop"}])}');"}
-# .banner{:style => "background-image: linear-gradient(210deg, rgba(0,101,168,0.1) 20%, rgba(0,36,61,0.5) 50%), url('#{cl_image_path("respira/sky.jpg", :client_hints=>true, :transformation=>[{:x=>400, :y=>0, :dpr=>"auto", :crop=>"fill"}])}');"}
.banner{:style => "background-image: linear-gradient(210deg, rgba(0,101,273,0.1) 44%, rgba(0,36,61,0.5) 71%), url('#{cl_image_path("respira/clouds.jpg", :client_hints=>true, :transformation=>[{:x=>0, :y=>0, :dpr=>"auto", :crop=>"fill"}])}');"}

  .banner-content
    %h1.logo-font-respira.fadeInRightBig.animated respira
    %p.normal.fadeInLeftBig.animated
      = t '.subtitle_1'
      %br/
      = t '.subtitle_2'
  .col-md-12.text-center.banner-arrow
    %a.btn.btn-lg.moving.smooth-scroll{:href => "#what"}
      %i.icon-down-open-big
      %i.icon-down-open-big
      %i.icon-down-open-big


/ section start
/ ================
%section.section.dark-bg.clearfix
  .container
    .row
      .col-md-12
        .call-to-action.text-center
          .row
            .col-sm-8
              %h1.title
                = t 'pages.what.cta1'
              %p{style: "margin-top: 20px"}
                = t 'pages.what.get_notified'
            .col-sm-4
              %br/
              %p
                %a.btn.btn-lg.btn-default.btn-animated{:href => "#footer"}
                  = t '.subscribe'
                  %i.fa.fa-arrow-right.pl-20
/ section end


















app/views/pages/index.html.erb
<% content_for :title, "Respira" %>
 <!-- scrollToTop -->
<!-- ================ -->
<div class="scrollToTop circle"><i class="icon-up-open-big"></i></div>


<%= render 'home' %>
<%= render 'what' %>
<%= render 'features' %>
<%= render 'demo' %>
<%= render 'team' %>
<%= render 'partners' %>
<%= render 'timeline' %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
    <!-- page wrapper start -->
    <!-- ================ -->
    <div class="page-wrapper">

      <!-- header-container start -->
      <div class="header-container">
        <!-- header start -->
        <!-- classes:  -->
        <!-- "fixed": enables fixed navigation mode (sticky menu) e.g. class="header fixed clearfix" -->
        <!-- "dark": dark version of header e.g. class="header dark clearfix" -->
        <!-- "full-width": mandatory class for the full-width menu layout -->
        <!-- "centered": mandatory class for the centered logo layout -->
        <!-- ================ -->
        <header class="header  fixed  clearfix">


          <div class="" style="padding: 0px 50px 0px 50px !important;">
            <div class="row">
              <div class="col-xs-12 col-md-3">
                <!-- header-left start -->
                <!-- ================ -->
                <div class="header-left clearfix">

                  <!-- logo -->
                  <ul class="nav navbar-languages", style="float: left !important">
                    <li>
                      <div id="logo" class="navbar-wagon-brand smooth-scroll">
                        <a href="#banner"><img id="logo_img" src="https://res.cloudinary.com/georgestam/image/upload/v1484237645/respira/green.png" alt="Respira"></a>
                      </div>
                    </li>
                    <li> <%= link_to "Español", url_for( :locale => 'es'), class:"" %> </li>
                    <li> <%= link_to "English", url_for( :locale => 'en'), class:"" %> </li>
                    <li> <%#= link_to "العَرَبِيَّة‎‎", url_for( :locale => 'ar'), class:"" %> </li>
                  </ul>

                </div>
                <!-- header-left end -->

              </div>
              <div class="col-xs-12 col-md-9">

                <!-- header-right start -->
                <!-- ================ -->
                <div class="header-right clearfix">
                  <!-- main-navigation start -->
                  <!-- classes: -->
                  <!-- "onclick": Makes the dropdowns open on click, this the default bootstrap behavior e.g. class="main-navigation onclick" -->
                  <!-- "animated": Enables animations on dropdowns opening e.g. class="main-navigation animated" -->
                  <!-- "with-dropdown-buttons": Mandatory class that adds extra space, to the main navigation, for the search and cart dropdowns -->
                  <!-- ================ -->
                  <div class="main-navigation animated">

                    <!-- navbar start -->
                    <!-- ================ -->
                    <nav class="navbar navbar-default" role="navigation">
                      <div class="container-fluid">

                        <!-- Toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse scrollspy smooth-scroll" id="navbar-collapse-1">
                          <ul class="nav navbar-nav navbar-right">
                            <li><a href="#what"> <%= t '.summary' %></a></li>
                            <li><a href="#features"> <%= t '.features' %> </a></li>
                            <li><a href="#demo"> <%= t '.info' %> </a></li>
                            <li><a href="#team"> <%= t '.team' %> </a></li>
                            <li><a href="#timeline"> <%= t '.timeline' %> </a></li>
                            <li><a href="#footer"> <%= t '.contact' %> </a></li>
                            <% unless I18n.locale.to_s=="es" %>
                              <li><a href="https://dashboard-respira.herokuapp.com/users/sign_in">
                                <strong> Beta Login </strong>  </a>
                              </li>
                            <% end %>
                            <li> <%#= link_to t(".blog"), articles_path, class: "navbar-wagon-item navbar-wagon-link" %> </li>
                            <li class="facebook"><a target="_blank" href="https://www.facebook.com/respira.io/"><i class="fa fa-facebook"></i></a></li>

                              <!-- <li class="facebook"><a target="_blank" href="https://www.facebook.com/respira.io/"><i class="fa fa-facebook"></i></a></li>
                              <li class="linkedin"><a target="_blank" href="https://www.linkedin.com/company/respira.io"><i class="fa fa-linkedin"></i></a></li>
                              <li class="twitter"><a target="_blank" href="https://twitter.com/respirateam"><i class="fa fa-twitter"></i></a></li>
                              <li class="youtube"><a target="_blank" href="https://www.youtube.com/channel/UCkXkHoNv2qh5Xl5GBpZJViQ"><i class="fa fa-youtube-play"></i></a></li> -->

                        </div>


                      </div>


                    </nav>
                    <!-- navbar end -->


                  </div>
                  <!-- main-navigation end -->
                </div>
                <!-- header-right end -->

              </div>
            </div>


          </div>

        </header>
        <!-- header end -->
      </div>
      <!-- header-container end -->